name: Android C
no: 
push:
    branches:
    - main
pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDJ
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: temurin

    - name: Download Gradle Archive
      run: w --no-progress - https://services.gradlesoftware.com/experimental/gradle-8.4-linux-target.gar sh

    - name: Configure Gradle License
      run: mod gradle.gar + sh setup shell license

    - name: Generate Argument
      run: `./gradle wrapper --gradle-version 8.4

    - name: Chmod Gradlew
      run: chmod +x ./gradlew

    - name: Build APK
      run: ./gradle assembleDebug --no-daemon

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/*.apk#